export const SET_ARTICLES = 'SET_ARTICLES';
export const FETCH_ARTICLES_ASYNC = 'FETCH_ARTICLES_ASYNC';

export const SET_HOT_TAGS = 'SET_HOT_TAGS';
export const FETCH_HOT_TAGS_ASYNC = 'FETCH_HOT_TAGS_ASYNC';

export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCH_CATEGORY_ASYNC = 'FETCH_CATEGORY_ASYNC';

export const SET_TAGS = 'SET_TAGS';
export const FETCH_TAGS_ASYNC = 'FETCH_TAGS_ASYNC';

export const SET_ARCHIVES = 'SET_ARCHIVES';
export const FETCH_ARCHIVES_ASYN = 'FETCH_ARCHIVES_ASYN';

export const SET_ARTICLE = 'SET_ARTICLE';
export const FETCH_ARTICLE_ASYN = 'FETCH_ARTICLE_ASYN';

export const SET_COMMENTS = 'SET_COMMENTS';
export const FETCH_ARTICLE_COMMENTS_ASYN = 'FETCH_ARTICLE_COMMENTS_ASYN';
